name: stackwealth_news
description: demo project
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc:
  flutter:
    sdk: flutter
  flutter_bloc:
  flutter_localizations:
    sdk: flutter
  intl:
  cached_network_image:
  equatable:
  infinite_scroll_pagination:
  dartz:
  dio:
  json_annotation:
  flutter_dotenv:
  provider:
  internet_connection_checker:
  go_router: 15.1.0
  animated_splash_screen:
  get:
  page_transition:
#  velocity_x:
  flutter_svg_provider:
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  flutter_gen_runner:
  json_serializable:
  mockito:
  mocktail:
#  very_good_analysis:

dependency_overrides:
  velocity_x:
    path: lib/forked_package/velocity/velocity_x-4.2.1



flutter_icons:
  android: ic_launcher
  image_path: assets/images/logo.png
  ios: false
  remove_alpha_ios: false

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
        - asset: assets/fonts/PoppinsExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PoppinsLight.ttf
          weight: 300
    - family: PT Serif
      fonts:
        - asset: assets/fonts/PTSerifBold.ttf
          weight: 700
        - asset: assets/fonts/PTSerifRegular.ttf
          weight: 400

